### ISSUE TITLE
Implement exclude filter for all sync operations

### ISSUE THREAD

**Issue by nerijus** [gogglesmm/gogglesmm#41]
How do I exclude some directories from the sync? I entered full folder name in "Folders:" under "Exclude Filter" in Sync dialog, but the files are still found in that folder.

**Comment by gogglesguy** [comment]
Currently the exclude filters are only used during importing of new files and are ignored during other sync operations (like update or delete). It never matches against the full absolute path name, but rather matches against the individual directory names it is about to enter. Same thing for the file filter, which only matches the filename and not against the full pathname.

This was added back in the days when an user tried ignore all directories named "mp3" when importing his music directory.

**Comment by nerijus** [comment]
Is it possible to not ignore it when syncing?

**Comment by gogglesguy** [comment]
It is still used during syncing but only when you are importing new files. What are you trying to accomplish? Only update/delete tracks that don't match the filters?

**Comment by nerijus** [comment]
Yes, I want to remove some files from the db.

**Comment by gogglesguy** [comment]
Ah ok, that's currently not implemented. I don't see no reason why this couldn't be added however.

Also "files are still found in that folder", sync doesn't remove files, it merely removes them from the database.

**Comment by nerijus** [comment]
BTW, how do I enter more than 1 folder in "Exclude Filter"?

**Comment by gogglesguy** [comment]
Separate by , or |

**Comment by gogglesguy** [comment]
Available in https://github.com/gogglesmm/gogglesmm/releases/tag/1.0.10

**Comment by nerijus** [comment]
I press Sync in the "Sync Folder..." dialog and it hangs writing "Clearing Files.." in the status bar.

**Comment by gogglesguy** [comment]
Thanks for testing. Just committed a fix to stable which I think fixes your issue.

**Comment by gogglesguy** [comment]
Another 2 fixes as well.

**Comment by nerijus** [comment]
Still the same - "Clearing Files.." in the status bar and cannot exit.

**Comment by gogglesguy** [comment]
Yikes.... duh..... your issue was actually a problem in the directory filter (infinite loop that was easy to reproduce). The other issue fixed yesterday were critical though...  but It is fixed now.

**Comment by nerijus** [comment]
Now it's OK, but I entered folder name (without path) in Exclude Filter->Folders, pressed Sync, but files in that folder are still found.

**Comment by gogglesguy** [comment]
Meaning they're still imported? What sync operations did you select?

**Comment by nerijus** [comment]
I better say they are still not deleted from the db, as they were imported earlier.
Sync options selected are the first 2, tried to select the 3rd one (Update existing tracks: All), nothing changed, the test file is still found in db.

**Comment by gogglesguy** [comment]
Ah, ok. That's not how it is implemented at the moment. They are exclude filters, so only files that don't match the filter will be removed. In the same way during import only files that don't match the filter will be imported. Breaking this symmetry would probably confusing

**Comment by nerijus** [comment]
Let's say I have "test" in Exclude Filter->Folders. Do you mean that when I press Sync, all the files in db will be removed, and only files in 'test' folder will be left in the db?

**Comment by gogglesguy** [comment]
It depends on the sync option you've selected:

- If you have selected "Remove tracks found in folder from database" then all files in that folder will be removed from the database except for the ones matching "test".

- If you have selected "Remove tracks that have been deleted from disk" then all files that  used to be in that folder (no longer accessible) will be removed from the databases except for the ones matching "test".

**Comment by nerijus** [comment]
I don't understand it - in both cases you say "then all files in that folder will be removed from the database except for the ones matching "test"." What's the difference then between those 2 options?

**Comment by gogglesguy** [comment]
Option 2 only removes files if they are no longer on disk. This is your typical case of cleaning up your database for files that were externally removed.  Option 1 allows you to remove whole (sub)folders from your database even if those files still exist.

**Comment by nerijus** [comment]
Well, that's probably not very intuitive. I tried to select the last option, it left the files in test folder only. Then I selected the first 3 options, and then again all the files with the test folder are in db.

So my first question remains - how do I remove files from some folders from the db?

**Comment by gogglesguy** [comment]
> Well, that's probably not very intuitive. 

I'm open to suggestions on how to make it more clearer. 

> I tried to select the last option, it left the files in test folder only.

Just as I just told you it would.

> Then I selected the first 3 options, and then again all the files with the test folder are in db.

Yes, you just imported all the same files again, except for the ones matching "test" which were already in the database. If you had removed the remaining files in the database and then imported the files, they would no longer be there. Of course this is not optimal, ideally you wouldn't have to remove all files from the database in order to remove certain files.

**Comment by nerijus** [comment]
For me the clearest would be to remove excluded files from the db when I press Sync without bothering about sync operations.

**Comment by gogglesguy** [comment]
Please see issue #43 for further discussion.
